name: ci
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        npm-test:
        - i18n_extract
        - lint
        - test
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: '.nvmrc'
    - run: make requirements
    - run: make test NPM_TESTS=build
    - run: make test NPM_TESTS=${{ matrix.npm-test }}
    - name: Coverage
      if: matrix.npm-test == 'test'
      uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
